### ISSUE TITLE
Outdated ansi-regex Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by DevRahim** [newrelic/node-newrelic#1105]
![Screenshot 2022-02-24 at 6 06 10 PM](https://user-images.githubusercontent.com/18681922/155525244-809fd537-578a-469e-85f3-ba3665204a45.png)
We are using this library in our all staging and prod environments. This issue is must be resolved asap.

**Comment by michaelgoin** [comment]
Hi @DevRahim,

I appreciate your concern and sorry you are getting warnings like this. I am wondering if Snyk is having issues at this point. 

Would you be willing to share the supposed vulnerable dependency path?

As of Node.js agent version `8.8.0`, the agent is referencing `@grpc/grpc-js@^1.5.5` which uses `proto-loader@^0.6.9` and we are referencing `proto-loader@^0.6.9` directly, as well. These both eventually resolve down to `ansi-regex^5.0.1`. This is the back ported fix: https://github.com/chalk/ansi-regex/releases/tag/v5.0.1.

The only old usage we have of `ansi-regex` that I am aware of are via our dev dependencies (an internal CLI and tap test runner).

In our own Snyk scans we are not getting any sort of warning as of agent version `8.8.0`.

It is also worth noting this is not exploitable in the context of the agent. The proto loader is used for generating grpc client for sending data only. The ansi-regex dependency will never be ran on untrusted user input.

**Comment by DevRahim** [comment]
Hi @michaelgoin 
Thanks for your response.

I am attaching the Detailed Path Screenshot. Please have a look.
![Screenshot 2022-02-25 at 6 51 33 PM](https://user-images.githubusercontent.com/18681922/155722340-ebceb3ac-eba5-488c-8618-4f930d9e11c7.png)

**Comment by michaelgoin** [comment]
Hi @DevRahim,

That is interesting. Due to how the deps are imported, strip-ansi and ansi-regex should be newer in that chain.

But it also looks like Snyk is noticing that and giving recommendations:

> Your dependencies are out of date, otherwise you would be using a newer ansi-regex than ansi-regex@5.0.0. Try relocking your lockfile or deleting `node_modules`, reinstalling and running snyk wizard...

My guess aligns with Snyk's message in that likely the lockfile is not updating and as such is pinning these sub-deps for this security scan. I'd check if the lockfile is indeed representing those older versions and if so, try to regenerate.

For reference, here's the dependency tree from Snyk for ansi-regex showing how those versions should resolve (some may be newer but shouldn't be older):

![Screen Shot 2022-02-25 at 9 18 19 AM](https://user-images.githubusercontent.com/11223178/155758977-6c1bce20-82f4-403b-b6b8-0b0cc4c9bf74.png)

**Comment by michaelgoin** [comment]
Closing this out as we cannot confirm an existing issue and this has been open since February.
