### ISSUE TITLE
Logging: Collector - adhere to data usage metrics specification

### ISSUE THREAD

**Issue by coreyarnold** [newrelic/node-newrelic#1180]
Implement the [data usage metrics specification](https://source.datanerd.us/agents/agent-specs/blob/main/Data-Usage-Supportability-Metrics.md)

Generate top level metrics for the following endpoints
- [ ] Collector

Generate sub metrics for the collector endpoints where possible
- [ ] [Collector endpoints](https://source.datanerd.us/agents/agent-specs/blob/main/README.md)
- [ ] [logging endpoint](https://source.datanerd.us/agents/agent-specs/pull/570/files#diff-fdbbc261f836d83d3ffe5d685d33069c53f989eb54c57c2df547378acf8dd572)

Update the agent spec readme
- [ ] Update [readme](https://source.datanerd.us/agents/agent-specs/blob/main/README.md) to reflect adherence.

**Comment by garbados** [comment]
In order to determine the byte size of a payload, we will need to log metrics from around https://github.com/newrelic/node-newrelic/blob/main/lib/collector/remote-method.js#L91 , after the payload is serialized but before it is sent. This will require passing the agent to the `RemoteMethod` class, which may not be desirable.

**Comment by coreyarnold** [comment]
@garbados I updated the task list to callout the new log endpoint and point at the open PR.
