### ISSUE TITLE
newrelic package uses vulnerable protobufjs version, CVE-2022-25878

### ISSUE THREAD

**Issue by garymartyn** [newrelic/node-newrelic#1227]
Hi all, we are seeing a high level vulnerability in the latest new relic package version

https://snyk.io/vuln/SNYK-JS-PROTOBUFJS-2441248

Snyk report:
 Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-PROTOBUFJS-2441248] in protobufjs@6.11.2
    introduced by newrelic@8.13.1 > @grpc/proto-loader@0.6.12 > protobufjs@6.11.2 and 1 other path(s)
  This issue was fixed in versions: 6.11.3

version/s this fix vuln fixed in:
protobufjs version 6.11.3 or higher.

**Comment by jordigh** [comment]
Thank you for your report. We seem to be having some trouble with our connexion to the Snyk broker at the moment, but that should be fixed by tomorrow so that in the future we can notice these problems before you or any other of our customers do.

In the meantime, I have manually opened a [PR to fix this](https://github.com/newrelic/node-newrelic/pull/1228/files).
