### ISSUE TITLE
Upgrading to new relic agent 9.8.0 makes logging library log "undefined" for any input

### ISSUE THREAD

**Issue by jakewins** [newrelic/node-newrelic#1483]
## Description

I have an existing typescript project, with winston logging configured and new relic agent version 8.9.1.

When running with new relic 8.9.1, my repro program outputs:

    Hello, world!
    
When upgrade to new relic 9.8.0, the program outputs:

    undefined

## Expected Behavior

I expected that upgrading a working deployment would not affect a logging library from another vendor, and my program would continue printing "Hello, world!".

## Steps to Reproduce

Here is a repro: https://github.com/jakewins/nr-undefined-logging-repro

## Your Environment

There is a docker file in the repro above that describes the deployment environment, versions and code.

## Additional context

I'm a bit shocked that this is happening, is new relic somehow instrumenting winston behind the scenes? Does it do this for other libraries as well? Is there a list somewhere of which ones, and how do I turn any such instrumentation off?

**Comment by jakewins** [comment]
I should add: The source for this is from trying to upgrade `newrelic` in an existing production app, where logging and new relic both currently work fine. We're upgrading because y'alls UI says we need to. The app is working fine on version `8.9.1`, and logging breaks when we upgrade to `9.8.0`. I haven't tested versions in between.

**Comment by jordigh** [comment]
I'm working on puzzling this out, but something is funny with the original code. This also returns `undefined` for me, without any New Relic instrumentation. It seems like there is something odd going on with the `timestamp` formatter combined with the `Console` transport. Note that you are not actually getting a timestamp. Is this the right way to use the `Console` transport? If I write something like this, I do get a timestamp, with or without New Relic instrumentation:

```js
"use strict";
require('newrelic')
const winston = require("winston")
const logger = winston.createLogger({
  transports: [
    new winston.transports.Console({
      format: winston.format.combine(winston.format.timestamp(), winston.format.json()),
    })
  ]
})

logger.info('Hello, world!')
```

**Comment by jordigh** [comment]
I believe the problem is that you're missing what Winston calls a "finalizing format":

https://github.com/winstonjs/winston/issues/1202

https://github.com/winstonjs/winston/issues/1476

It happens to coincidentally kind of work without this in your original version, but our instrumentation attempts to add another formatter to the one you have. The combination of New Relic's formatter with your own ends up resulting in `undefined` as output.

I think you have one of two options:

1. add a finalizing formatter, one of
  *  `json`
  * `logstash`
  *  `printf`
  * `prettyPrint`
  * `simple`
2. OR disable New Relic's instrumentation of winston as described by @mrickard, by setting `application_logging.enabled` to `false` in your config.
