### ISSUE TITLE
Uncaught exception in winston instrumentation when adding loggers

### ISSUE THREAD

**Issue by noynir** [newrelic/node-newrelic#1523]
## Description
When using new relic and winston logger. adding loggers results in an Uncaught exception

## Expected Behavior
No exception when adding loggers.

`"uncaughtException: this.loggers.has is not a function\nTypeError: this.loggers.has is not a function\n    at exports.Container.wrappedAdd [as add] (/home/node/app/node_modules/newrelic/lib/instrumentation/winston.js:54:41)\n ... `

## Steps to Reproduce

1. Import winston.
2. import new relic package.
3. Add logger with  `winston.loggers.add`

## Your Environment
NODE 16 LTS
alpine-linux

## Additional context
I Believe the problem is here. 
`this` is not in proper context.

https://github.com/newrelic/node-newrelic/blob/61ce7c44463329eb0f8a6beb50b08ddc23194166/lib/instrumentation/winston.js#L54

**Comment by kirlev** [comment]
@bizob2828 We are having the same issue.
newrelic agent version: 10.3.2
winston version: 2.4.5

The agent worked fine until we added custom instrumentation with `startSegment`, then we started receiving the above error.
The cause is calling the `winston.loggers.add` function in our app and then the error is raised in line `node_modules/newrelic/lib/instrumentation/winston.js:54:41`

Can you please provide a solution?
