### ISSUE TITLE
NodeJS:Bluebird@3.7.2 context propgation not happening

### ISSUE THREAD

**Issue by ChandrasekharPo-Kore** [newrelic/node-newrelic#1537]
# Bluebird@3.7.2 context propgation not happening 

As BlueBird uses either process.nextTick or setImmediate to run drainQueues ( this calls all the callbacks of the resolved promises ). All the resolved callbacks are under the asynchronous resource that does the initial scheduling, the context propagation is not happening as expected. All the resolved callbacks are run in the context of the async resource that does the bluebird schedule.

The transaction that exists before the Promise creation is not available in the resolved callback( happening in consistently) but gets a different transaction 

## Nodejs

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

[TIP]:  # ( Include as many relevant details about your environment as possible. )
Node version: 16.40
Ubutnu 20
bluebird@^3.7.2
newrelic@9.11.0 ( async_local_context: true )

Attached the script demonstrating the problem.
[understandbluebird.js.txt](https://github.com/newrelic/node-newrelic/files/10950323/understandbluebird.js.txt)

Output:
transaction_1:  a283508c1642a1b4 
transaction_2:  7cf4bb194007188c

resolved:transaction_1:  a283508c1642a1b4
resolved:transaction_2:  a283508c1642a1b4 (this is not expected, it should have been 7cf4bb194007188c)

**Comment by ChandrasekharPo-Kore** [comment]
Evaluating bluebird config to enable asynchooks. Will keep everyone posted on the results.

**Comment by bizob2828** [comment]
@ChandrasekharPo-Kore thanks for reporting this case.  It's an interesting one and I think it can be solved by using our legacy context manager.  This means making sure you have `feature_flag.async_local_context = false`.  When the async local context manager is enabled it does not instrument [process.nextTick](https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/core/timers.js#L17), but instead relies on async hooks to properly propagate.  However, since bluebird may not be async hooks compliant, this may require specific, new instrumentation for bluebird so we will dig into it but I think in the near term your solution can be using legacy context manager.

**Comment by bizob2828** [comment]
> Evaluating bluebird config to enable asynchooks. Will keep everyone posted on the results.

@ChandrasekharPo-Kore can you clarify what you mean here?
