### ISSUE TITLE
Instrument native fetch

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1773]
### Description
In July 2022 we did research to see what it'd take to support native fetch.  Although it's a little clunky around when to register the instrumentation it does work. Work was tracked in https://github.com/bizob2828/node-newrelic/tree/fetch-research. The integration tests for global fetch, which were adapted from the undici versioned tests are failing. Since then we changed our CJS instrumentation hooks to require-in-the-middle but the spirit of that research should still hold true

### Acceptance Criteria
Customers using global fetch will see external calls tracked appropriately

**Comment by darrensmithwtc** [comment]
Hi

This issue is affecting two projects on a new client currently.  I was hoping enabling the old feature_flag for undici would work but clearly not as I've found this Issue :)

We're currently trying to add a workaround for now using startSegment to capture the metrics at least, but presumably there is no way for it to show up in External Entities view until your PR is merged and the new agent is released right?

Thanks

**Comment by bizob2828** [comment]
@darrensmithwtc v11.1.0 just got released with support for native fetch.

**Comment by darrensmithwtc** [comment]
> @darrensmithwtc v11.1.0 just got released with support for native fetch.

Nice one! Thank you for confirming @bizob2828 - Appreciated.  And a Lambda Layer update too! Bonus Points! :1st_place_medal:
