### ISSUE TITLE
Add BunJS compatibility

### ISSUE THREAD

**Issue by rodolfofrancoyummy** [newrelic/node-newrelic#1959]
## Is your feature request related to a problem? Please describe.
I'm trying to have the New Relic agent work inside a BunJS app. Starting the app using `bun run -r newrelic src/index.ts` is not working and importing the library in the first line of the entry file as `import newrelic from 'newrelic'` is also not working. 

## Feature Description
To be able to preload New Relic module and connect to my APM.

## Describe Alternatives
Rewrite app from BunJS to NodeJS 

## Additional context
ElysiaJS Framework

## Priority
Nice to Have

**Comment by ygerass** [comment]
Cannot prioritize this issue at the moment. Closing now, may reconsider in the future.

**Comment by dgpt** [comment]
adding my +1 to this feature request 🥺

**Comment by canab** [comment]
We are payed customer and we are migrating to Bun. If Newrelic does not want to support Bun, we will have to migrate from newrelic too.

**Comment by Winfle** [comment]
@canab it is fine. I think, it is hard / risky to add a support of a runtime, that written in completely different languge.
I think that Bun has low usage compared to NodeJS, thats why its coverage won't be possible in nearest future

**Comment by chaos-dremel** [comment]
Newrelic agent can be used with bun. But there are several caveats and limitations

To use newrelic-agent you need:
1. Install newrelic agent without optional dependencies (first of all without @newrelic/native-metrics because it will not work with bun). Something like `npm i --no-optional newrelic` will help
2. Use node style `server.listen` and not `bun.serve`

Limitations:
1. No info for external http requests (no `web external` on transaction time graph). Everything is `node.js`. But transaction time is accurate
2. Very limited info in `Node VMs` section

**Comment by nigel-loops** [comment]
Migrating to datadog because of lack of bun support with new relic library.
