### ISSUE TITLE
[spike] Research how to answer questions around library, agent, and node versions

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2132]
### Description
Our metric collection around library usage is rigid.  We cannot answer the following questions easily:
 * Which agent version is a customer using with a specific 3rd party library version?
 * Which OS is a customer using with a specific agent version?
 * Which OS is a customer using with a specific 3rd party library version?
 * Which account is using a specific 3rd party library version?

### Acceptance Criteria
Research how to answer the questions above.  There are probably more questions we want to answer as well.  We have access to a system called BDMS but we need to figure out if there's any work needed to make these queries.

**Comment by jsumners-nr** [comment]
I look forward to us being able to answer these questions. I am very surprised we cannot do so already.

**Comment by jsumners-nr** [comment]
Here's what I have found in regard to this issue:

1. The "BMDS" (Basic Metadata Service) is a Java application that receives events and stores the information in a table.
2. The BMDS app has a list of modules to recognize in event data so that information about them can be stored in the table. This is a hard coded list that must be updated by an engineer for any modules we are interested in querying.
3. There is a traditional DBMS table that contains the raw information from the events that we could query, but we need to request access to the read replica in order to determine if this would solve our needs.
4. The APM Services team has started researching a project that would make the data in 3 much easier to query and would store the data in NRDB. We should express support for this initiative.

**Comment by bizob2828** [comment]
Are you suggesting we wait for the APM services team to do their research? If so, can you link that work here so we can track it?

**Comment by jsumners-nr** [comment]
Regarding access to the current data, we'd need access to something called "DataOS" and some specific views within it https://newrelic.slack.com/archives/C02JWDPGU14/p1715793792715619?thread_ts=1715768785.766389&cid=C02JWDPGU14

Regarding the APM services team research, it is outlined in https://newrelic.atlassian.net/wiki/spaces/~55705836d78a61f2fb457d9b61610b2d477da8/blog/2024/03/06/3259466062/The+future+of+APM+Environment+Data

https://newrelic.slack.com/archives/C01UQHE9JG2/p1715690604544649
