### ISSUE TITLE
Create a utility that extracts account id from aws access key

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2175]
### Description
In <link to cloud relationship ticket>, we will be providing the ARN of the resource getting called in AWS.  We have all the information to construct the ARN.  However the account id is decoded from aws access key.  You can see this [writeup](https://hackingthe.cloud/aws/enumeration/get-account-id-from-keys/#decode-the-access-key) about how to decode in python.  Also the [java agent](https://github.com/newrelic/newrelic-java-agent/pull/1868/files#diff-5afe635fdec77504c272a6aa159a5b529551aa120bff833baf87795dd74ab78a) has ported the logic.  

### Acceptance Criteria
As a Node.js agent engineer I want the ability to decode the aws access key to obtain the account id of the running request.

**Comment by jsumners-nr** [comment]
I spent almost two days on this. I have tried utilizing existing base32 decoders, I have tried implementing my own base32 decoder, and I have tried porting the Java team's decoder. None of my approaches have come anywhere close to decoding the value correctly. I believe we are encountering an integer overflow when attempting to apply masks to either reconstruct the integer from the base32 decode and/or when attempting to mask that integer with the known magic value (`0x7fffffffff80`); bitwise operations in JavaScript operate on 32bit integers.

In the end, my conclusion is that this is at the very least too brittle even if we were to successfully get the decode to work. The access key id format _has_ changed multiple times over the years, and there's no guarantee that it won't change again in the future. If it does change in the future, we'd be left with the difficult task of reverse engineering the changes in order to keep up.

**Comment by bizob2828** [comment]
I agree. it'll be good to post the code snippet. I have some here and works fine until doing the bitwise operation and right shifting 7 bits

```js
const base32 = require('hi-base32')
const keyId = accessKey.slice(4)
const decodedBytes = base32.decode.asBytes(keyId) 
console.log(decodedBytes)

const id = convert(decodedBytes.slice(0, 6))

console.log('decoded id', id)

const mask = parseInt("0x7fffffffff80", 16) 
console.log('decoded mask', mask)
const bw = id & mask
console.log('bw', bw)
const res = bw >> 7
return res
