### ISSUE TITLE
The error.class property of http spans and streaming spans should be a string containing HTTP status code

### ISSUE THREAD

**Issue by mrickard** [newrelic/node-newrelic#2180]
### Description
According to [the Agent Spec](https://source.datanerd.us/agents/agent-specs/blob/main/Span-Events.md#http-response-code-errors), 
> _If_ the agent supports synthesizing errors based [on] the HTTP response code, the following attributes **MUST** be added to the span...

and lists the attributes `error.message`, `error.class`, and `error.expected` if the error has been marked as an expected error.

Currently, the Node agent does add these attributes to the span if the span context has an error and if transactions are not set to ignore the relevant status code, in both [span-event](https://github.com/newrelic/node-newrelic/blob/main/lib/spans/span-event.js#L92-L101) and [streaming-span-event](https://github.com/newrelic/node-newrelic/blob/main/lib/spans/span-event.js#L92-L101). In both cases, `error.class` is defined from `spanContext.errorDetails.type`. 

The actual error details are defined in the Error Helper's [extractErrorInformation method](https://github.com/newrelic/node-newrelic/blob/main/lib/errors/helper.js#L52), which currently is not resetting the `type` to contain the HTTP statusCode, though status code is included in the error message. 

Running the [transaction errors integration test](https://github.com/newrelic/node-newrelic/blob/main/test/integration/transaction/errors.tap.js), shows the `error.class` to be defined simply as the default definition`Error` in the case of HTTP transaction errors. 

In the case of HTTP errors, the agent should populate the `errorDetails.type` with a string consisting of the numerical HTTP Status Code.

### Acceptance Criteria

* The Error Helper's`extractErrorInformation` should be updated to provide a string containing the numerical HTTP Status Code in the event of an HTTP error.
* There should be additions to our tests to verify this. 

### Additional Context

Spans derive their error properties from the SpanContext's error property. That is derived from the transaction's `_linkExceptionToSegment`, [here](https://github.com/newrelic/node-newrelic/blob/main/lib/transaction/index.js#L808-L814), in [errors.getErrorDetails](https://github.com/newrelic/node-newrelic/blob/main/lib/errors/index.js#L32-L37), which calls the Error Helper's `extractErrorInformation` method.

**Comment by bizob2828** [comment]
This change feels too risky.  I did a lot of digging amongst language agents.  The java, and go agent only adds the `error.class` as the http response code to spans. I can't tell what .Net agent is doing. The other language agents are not doing this.  For us to only add to span events, it would be done in [span event](https://github.com/newrelic/node-newrelic/blob/main/lib/spans/span-event.js#L97) and [streaming span event](https://github.com/newrelic/node-newrelic/blob/main/lib/spans/streaming-span-event.js#L116). If we did it in the [error helper](https://github.com/newrelic/node-newrelic/blob/main/lib/errors/helper.js#L80) there are too many edge cases. In fact since the errors in [http instrumentation](https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/core/http.js#L258) are recorded before the statusCode exists, it'll never set `error.class` to the http response code.  I did some refactoring [here](https://github.com/mrickard/node-newrelic/commit/f460d888f58e0987eabb00cacdb241c93ac01e89) but it breaks a lot of other constructs, specifically around ignoring or marking  errors as expected by class name.
