### ISSUE TITLE
[spike] Research feasibility of instrumenting WebSocket

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2337]
### Description
In Node 22 they made [WebSocket global](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) stable.  We should research how we could instrument this client. We don't really have a published spec on how to handle web socket connections and when to create/end spans but maybe this could help facilitate that.  The outcome is a DACI on how to proceed.

### Additional context
Reach out to other language agent teams to see if they instrument any web socket clients and how they handle this.

**Comment by mrickard** [comment]
As I recall, there's a fundamental issue to overcome here: Websocket connections can be very long-running, but traces have a duration limit of 20 minutes (as per the tracing team). I think that explains the lack of clear spec on socket instrumentation: we've tended not to do it, because of the indeterminate duration.

**Comment by bizob2828** [comment]
We don't have to create transaction/traces for web socket connections though.  It's still worth researching
