### ISSUE TITLE
Drop use of ursa to support Node 10 and above

### ISSUE THREAD

**Issue by IdanAdar** [newrelic/node-newrelic#292]
First, why is it not possible to open issues for this repo: https://github.com/newrelic/node-native-metrics

Second, please see here: https://github.com/nodejs/node-gyp/issues/1575#issuecomment-468262250

It's not possible to use your package in newer Node releases because of your use of the very very very old an unmaintained ursa package somewhere along the way.

**Comment by astormnewrelic** [comment]
Idan, nice to meet you, glad you found us!

> First, why is it not possible to open issues for this repo: https://github.com/newrelic/node-native-metrics

The reason is -- reasons?  It's complicated, but the short version is having a single source for issues related to the Node Agent makes it easier for us to respond to issues out-of-band from the regular support workflow on GitHub.

Speaking of which -- the fastest way to officially resolve any issue with the Node Agent is via our standard support channels -- if this is _one of those™_ issues you can get started with [that over here](https://support.newrelic.com/).

As for your issue, we're happy to help troubleshoot, especially if it points to a problem with the Node Agent that other folks might be seeing.  That said,

1. We have lots of folks using the Node Agent and the native metrics modules on Node 10 without a issue

2. We don't _seem_ to use the `ursa` native module anywhere

3. If the native metrics module fails to compile our install script will fallback and download precompiled binaries

So this _may_ be a local issue. If I look over [your `pastebin`](https://pastebin.com/Xe4DTwqS), I do see the following starting on line 94

    install successful: _newrelic_native_metrics-3_1_2-native_metrics-64-linux-x64

    ursa@0.9.4 install     /home/jenkins/workspace/Certificates_Manager_develop/node_modules/ursa
    > node-gyp rebuild

The first line indicates that the the native metrics module was successfully downloaded, and the second and third line indicate that npm in starting to compile a **new** module -- `ursa`.

So, looking over all that, our best guess is that there's something else in your dependency tree that needs/wants the `ursa` module.

That is a guess though -- if you still think this is a problem with the native metrics module, can you provide us with a test/install case that reproduces the problem?

**Comment by IdanAdar** [comment]
Thanks for getting back to me! I guess we need to dig some more here...
