### ISSUE TITLE
Q: custom web transaction instrumentation & noticeError

### ISSUE THREAD

**Issue by hugebdu** [newrelic/node-newrelic#313]
Hello newrelic wizards,

we're using `newrelic.startWebTransaction('txName', false, promisifiedHandler)` API to instrument incoming [`grpc`](https://www.npmjs.com/package/grpc) calls since for now you do not instrument gRPC.

few Qs here:
1. in case the promise is rejected, do you report error implicitly or I have to call `newrelic.noticeError` in my `catch` clause?
2. currently I call `noticeError` explicitly, however looks like it is not connected to current transaction (created via `startWebTransaction`) - is there any way to use `startWebTransaction` + `noticeError` and to have the error being related to current transaction?

Thanks in advance.

D

**Comment by astormnewrelic** [comment]
@hugebdu Nice to meet you!  No wizards here, unfortunately, just programmers -- but we'll do our best to help you out.  

First -- the quickest/best way to get support for the agent is via our official support channels: https://support.newrelic.com/ -- submitting a ticket ensures the right eyes get on your issue in a timely manner, and gives you full access to the support and accounts teams.  

That said we're happy to back-channel help-out here as best we can. 

The short answer to your question is -- is depends.  Things get tricky with promises because while it often _looks_ like your code is running within the same transaction, due to the deferred nature of promises it often means by the time `noticeError` is called that the transaction has actually ended. So the more context you can provide how where/how things are called, the better we'll be able to help. 

To start with -- looking at your post you said

> newrelic.startWebTransaction('txName', false, promisifiedHandler)

What version of the agent are you using?  Or are you using some custom third party New Relic library? We're asking because looking at our [startWebTransaction](https://github.com/newrelic/node-newrelic/blob/master/api.js#L702) API, it only accepts two arguments, and the method you're calling accepts three.  

If you can fill us in on this, as well as share as much context about how and where you're putting your API calls, we'll be better able to help you reason through the best way to get your caught promises reporting their errors into New Relic with GRPC.

**Comment by hugebdu** [comment]
@astormnewrelic hi and thanks for quick reply

>  it only accepts two arguments, and the method you're calling accepts three.

indeed, my bad. mismatched with `startSegment`

> What version of the agent are you using?

v6.0.0

> If you can fill us in on this, as well as share as much context about how and where you're putting your API calls

ok, this one is a bit hacky :)
I'd do my best explaining it.
our current infrastructural wrapper around gRPC server emits events and does not allow any instrumentation around the actual handler. So what we're doing is tricking the agent (might be a problem):

```js
function setupNewrelicForServer(newrelic, grpcServer) {
  grpcServer.on('beforeCall', event => {
    newrelic.startWebTransaction(`${event.interface}.${event.method}`, () => new Promise((resolve, reject) => {
      event.transaction = {resolve, reject};
    }).catch(error => {
      newrelic.noticeError(error)
    }));
  });

  grpcServer.on('afterCall', event => {
    if (event.error) {
      event.transaction.reject(event.error);
    } else {
      event.transaction.resolve();
    }
  });
}
```

digging into your code I've seen you're using `async_hooks` - might be an issue with our current approach?

**Comment by astormnewrelic** [comment]
@hugebdu  Looking over that code -- I see that you're passing in a function to `startWebTransaction` that instantiates a new promise object.  As written, your code basically asks the agent

> Hey, New Relic agent -- start a transaction for me, and then instrument my creating this promise, and then stop the transaction when **this function** finishes executing. 

So the transaction is probably going to be finished before the code in `catch` runs, and will definitely be gone by the time or your `afterCall` handler has a chance to run.  

Take a look at [the doc block for `startWebTransaction`](https://github.com/newrelic/node-newrelic/blob/b33a182d71d713cd28b75e6bac126efe59e180be/api.js#L686) -- you should read the whole thing, but this code sample shows you how to start a transaction, and then get a reference to that transaction so _you_ can decide when it ends by calling its `end` method.  You'll probably need to restructure you code a bit, but this should let you get your `noticeError` calls in and come up with a way to instrument grpc the way you want.

Re: async_hooks -- yes, we use this to listen for the instantiation of native promises in order to provide instrumentation.

I _think_ the above should get you moving in the right direction, but if you still have questions please don't hesistate to ask. 

Speaking of questions -- the team's always interesting in hearing how folks are using NodeJS.  If you have a moment, would you mind sharing 

1. What version of NodeJS you're running
2. Are you using native promises, or a promise library?
3. What grpc library are you using to implement your server?
4. What grpc library are you using to make client calls?

**Comment by hugebdu** [comment]
@astormnewrelic thanks for the feedback, we will give it a try according to your suggestion.
as for your questions:
- node v10, moving in a few weeks to v12
- mostly bluebird and native
- we're using [`grpc`](https://www.npmjs.com/package/grpc) both for client & server, native addon flavour with some custom code generation built on top of [`protobufjs`](https://www.npmjs.com/package/protobufjs)

**Comment by astormnewrelic** [comment]
@hugebdu It's been around a week and half and we haven't heard from you -- can we assume you're all good?  

If not, please don't hesitate to let-us-known/re-open this issue. 

If so, do nothing, and best wishes with your end-of-year projects.
