### ISSUE TITLE
Node 13 support

### ISSUE THREAD

**Issue by AdrianSkierniewski** [newrelic/node-newrelic#315]
Hi,

We'd like to start using newrelic for our node.js apps, but we're already on node v13 and node version restriction in package.json prevent us from installing it.

```error newrelic@6.2.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <13.0.0".```

Are there any plans to support node v13 soon?

**Comment by alubbe** [comment]
This is blocking us as well in adopting newrelic - could you please share the roadmap for this?

**Comment by astormnewrelic** [comment]
Thanks all for chiming in about Node 13 support.

First: You can find our official support policy here -- https://github.com/newrelic/newrelic-telemetry-sdk-java 

TL;DR;

> New Relic will support the latest even versions of Node.js releases by the beginning of the following active long term support schedule. 

So right now we're not officially supporting the odd-numbered NodeJS branches.  If you disagree  with this I'd recommend a feature request via our formal support channels: https://support.newrelic.com/   (also -- the best way to request support for anything is through these channels -- right now GitHub issues is mostly  an engineering back channel -- shhhh)

Second: All that said (i.e. unofficially/pragmatically) -- if folks want to live on the bleeding edge they can -- right now that means 

1. Using a package manager like `yarn` and its `--ignore-engines` feature to ignore those requirements
2. Creating your own fork of the agent that removes the engines requirements

Because these odd numbered release eventually become the even numbered LTS versions -- if you run into problems with Node 13 **we are interested in hearing about them**

Finally: We know the above workarounds aren't always a fit for everyone -- there's been some talk on the team about just removing the max version requirements from our `package.json` file.  We'll leave this issue open for now while those discussions work their way through to a final decision, and then give you'all an update when there's one to give.

**Comment by alubbe** [comment]
Thanks for the great and nuanced overview. It's indeed a challenge to both not support newer versions and then hope for feedback on them ;)

Since you are discussing this internally, I would have a very pragmatic solution: Remove the max version requirement from `package.json` but add a `postinstall` script to print a warning message that the version is so recent that there may be bugs and ask for bug reports at this repo. What do you think?

**Comment by michaelgoin** [comment]
@AdrianSkierniewski  @alubbe,

With the most recent agent release, we've removed the engine upper-bound limit. So you should be able to experiment with Node 13 (and 14 when it is released) prior to our official support. 

Shortly, I'm going to be opening a GitHub issue where anything discovered can be added to help inform us when we get to official support time for 14.
