### ISSUE TITLE
Failed integrating with AWS DAX

### ISSUE THREAD

**Issue by seoker** [newrelic/node-newrelic#321]
Hi, I am currently integrating newrelic agent into our application.

I noticed that if I use AWS DAX as a replacement of DynamoDB client, I always got an error on every DB manipulation.

```
const dax = new AmazonDaxClient({ region: 'us-east-1', endpoints: ['some.endpoint'] });
const dbClient = new AWS.DynamoDB.DocumentClient({ service: dax });
await dbClient.query({ ... }).promise();
```

```
Cannot read property 'host' of undefined
error: TypeError: Cannot read property 'host' of undefined
    at DocumentClient.wrapOperation (/home/ec2-user/async_worker/node_modules/@newrelic/aws-sdk/lib/dynamodb.js:64:39)
    at DocumentClient.opRecorder (/home/ec2-user/async_worker/node_modules/newrelic/lib/shim/datastore-shim.js:411:24)
    at DocumentClient.wrapper [as get] (/home/ec2-user/async_worker/node_modules/newrelic/lib/shim/shim.js:927:33)
    ...
```

But a regular DynamoDB client works fine.
```
const ddb = new AWS.DynamoDB({ region: 'us-east-1' });
const dbClient = new AWS.DynamoDB.DocumentClient({ service: ddb });
await dbClient.query({ ... }).promise();
```

Tried `@newrelic/aws-sdk` but the issue remains.

**Comment by michaelgoin** [comment]
Hi @seoker ,

Sorry about the inconvenience. It looks like DAX as the service violates some hard assumptions we had built in. I get a different error on quick test (`IllegalArgumentException: Invalid hostport:some.endpoint`) but definitely the same negative outcome. Unless it is a straightforward issue to resolve, we may end up putting in defensive code to disable instrumentation for this situation.

If that is the case, let me know if DAX is something you'd want officially supported and we can capture as a feature request.

Thank you,

Michael

**Comment by seoker** [comment]
Hi @michaelgoin,

Thanks for the prompt reply. Just disabling the instrumentation on DAX is good to me in my case.

**Comment by michaelgoin** [comment]
@seoker you are right. fixed my test example and got the exact same error.

Thank you for letting us know disabling would be OK for your use case.

**Comment by jcreager** [comment]
> Unless it is a straightforward issue to resolve, we may end up putting in defensive code to disable instrumentation for this situation.

> But just disabling the instrumentation on DAX is good to me in my case

That would be great for our team as well.  This currently prevents us from using newer versions of the agent.  I think defensive makes sense.  I want metrics, but I don't want it to break my deployment.

> If that is the case, let me know if DAX is something you'd want officially supported and we can capture as a feature request.

I think it is important to support DAX if dynamo is being instrumented.  The same goes for any other feature in the aws-sdk that will be instrumented.  Either that or instrumentation should be very defensive.  Look at it this way.  A team could have no issues using dynamo and then suddenly have a broken deployment because DAX or anther feature that was not supported was enabled.  Debugging that can burn a lot of time.

Thank you for jumping on this issue.  Is there an ETA on when this will be resolved?

**Comment by michaelgoin** [comment]
Hi @jcreager,

No specific ETA at this time. Will keep y'all posted.

**Comment by jcreager** [comment]
Thanks @michaelgoin.

**Comment by seoker** [comment]
Hi @jcreager 

> That would be great for our team as well. This currently prevents us from using newer versions of the agent. I think defensive makes sense. I want metrics, but I don't want it to break my deployment.

May I know what version you are using that won't break even if DAX is used?
Thanks!

**Comment by jcreager** [comment]
@seoker `5.13.1`

**Comment by michaelgoin** [comment]
@seoker The `aws-sdk` wasn't rolled into the agent for auto-install until version 6.1.0. So any earlier version should avoid that.

**Comment by michaelgoin** [comment]
@jcreager @seoker,

A patch to avoid crashing has been published with `@newrelic/aws-sdk@1.1.2`. `host` and `port` will now be captured as 'unknown'. You can use immediately via manually installing that version or we will be releasing in the main agent soon.

Since this issue is in the main agent repo, I'll leave this open until this ships with the main agent.

**Comment by jcreager** [comment]
@michaelgoin Thanks for the update!

**Comment by michaelgoin** [comment]
A new version of the agent has been deployed including the new version of the `aws-sdk` instrumentation. Please let us know if you have further issues.
