### ISSUE TITLE
noticeError should take a callback when the error has been successfully sent to new relic 

### ISSUE THREAD

**Issue by devinrhode2** [newrelic/node-newrelic#323]
I would love to know when noticeError has finished sending an error to new relic.

The easiest thing would be to add a third parameter to noticeError, the best thing would be to have noticeError return a promise. I personally am partial to having a third parameter, and passing 1 argument to that callback, a boolean representing "success" (true) or "failed to send error" (false)

> I couldn't find a github repo for new relic browser JS, however, this repo clearly implements the noticeError function I am looking to edit.

**Comment by michaelgoin** [comment]
Hi @devinrhode2,

I see the comment: 

> I couldn't find a github repo for new relic browser JS, however, this repo clearly implements the noticeError function I am looking to edit.

If you are recommending this feature for the "Browsers" product / browser JS monitoring, you'll probably be best served starting through the support channels. I believe this is usually the best first stop: https://discuss.newrelic.com/c/feature-ideas.

Our Node agent is actually separate from the "browsers" product, even though we do provide a mechanism for injecting the browser agent into web pages.

As far as the Node agent, calling `noticeError()` and sending the data to the server are actually separate actions. The agent collects data and then sends to the server on a set interval. This means, if implemented, you may have to wait up to a minute for the callback to execute. I'm guessing that is not ideal.

Let me know if you did intend this for the Node agent, and still want this as a feature request. Otherwise, feel free to close or let me know and I can close for you.

Thank you,

Michael

**Comment by astormnewrelic** [comment]
Closing this out for lack of activity -- if this is still an issue or there's more to say don't hesitate to reopen/keep the conversation going and/or open a new issue.
