### ISSUE TITLE
Possible memory leak when run under ts-node

### ISSUE THREAD

**Issue by mastermatt** [newrelic/node-newrelic#337]
I'm investigating a memory leak in a production app that seems to be related to this library, but I'm not sure if it's the cause yet.
Unfortunately, we have been migrating infrastructure over the last few months and our monitoring wasn't tweaked right so I'm unable to say with certainty if this is a new issue, but I don't believe it is. 
The app is an express based API that runs ts-node in production, not pre-transpiled.
I spun up an instance in a lower environment, took a heap snapshot, ran its acceptance tests, then took another heap snapshot to compare. 
The tests generate a couple hundred requests and increases the memory ~17Mb. The vast majority of the retained space is instances of `TraceSegment` and `Transaction`.

<img width="806" alt="Screen Shot 2020-04-07 at 6 29 29 PM" src="https://user-images.githubusercontent.com/2789206/78731734-bf506f00-78fd-11ea-9672-ecb35513f65f.png">

Has anyone else had this issue? And what other info can I provide to help debugging? 
Digging around the code, it's unclear to me why the wrapped `nextTick` scopes would be retaining refs to Transactions. 

Node: 10.19.0
ts-node: 8.8.1
typescript: 3.8.3
newrelic: 6.5.0

**Comment by astormnewrelic** [comment]
@mastermatt Good to hear from you -- sorry it's always under "what the heck are these computers doing" circumstances.  

Also, (I think you know the drill here), if you need "official" New Relic support for this you'll want to reach out via our official support channels: https://support.newrelic.com -- we're always happy to help here _when we can_ -- but this isn't an official support channel and we might be silently pulled away on things.  Submitting a ticket to support is the best way to ensure the right eyes get on an issue.  

Thanks for digging into this and for providing a clear description of the behavior you're seeing so far.  There's nothing obvious that jumps out as being the root cause of this behavior.  We're definitely interested in getting to the bottom of it. 

I'm going to give a little context on what the `Transaction` and `TraceSegment` objects are for, take some wild guesses as to what's going on along the way, and then ask you a few more questions about your environment to further debugging. Apologies if this is redundant information -- but it sometimes helps to frame things for other folks who are newer to the agent and following along. 

## Context

Speaking broadly a `Transaction` represents, more or less, a single HTTP(s) request/response cycle and everything that happens within it.  Transactions _can_ represent any two arbitrary points in time in the life of your application, but in practice it's usually a single HTTP(s) request/response cycle.  

A `TraceSegment` represents a smaller unit of time _within_ a transaction.  It's usually measuring some specific thing that happened -- the amount of time an individual function took to execute is a common example.  At the end of a transaction each `TraceSegment` in a transaction is synthesized into other datatypes (nodes of a Transaction Trace, Span Event, etc.) that are eventually sent to New Relic.  

Memory wise, a `TraceSegment` _should_ be cleaned up by the time a transaction ends.  If they're not, then something is holding a reference to them open.  One example we've seen in the past is segments created in promises, and the promise is never resolved or rejected.  If a promise does some work that's instrumented, but never resolves, the trace segments can be held open while node waits for the promise to resolve.

So -- sometimes these issues are bugs in the agent, sometimes they're poorly behaving application code that the agent makes worse by doing more work (a small leak might become a bigger leak, etc.).  

We're definitely interested in tracking these down, but will need more context/help from you.

## Questions

First, you mentioned you're running an application in production using `ts-node`.  This raises a few question for us

- What flags are you invoking `ts-node` with when you run the application?
- If you manually compile/transpile the code to native javascript and run with node, is the leak present?

The main ts-node maintainer seems hesitant to commit to [whether ts-node is production ready or not](https://github.com/TypeStrong/ts-node/issues/104), so it would be good to pinpoint whether `ts-node` is the problem, or of it's something else

Second -- 

- What version of express are you using? 
- What are your express API endpoints doing?
- Are you using any third party promise libraries?
- Is the set of endpoints you have small enough that it would be possible to run some tests and determine if there's a specific endpoint with this leak, or its all of them?
- What other libraries are you using to fetch data?

Our end goal here is to get a reproduction of the issue that anyone can run.  Once we can reproduce the issue, we can usually determine pretty quickly if it's a bug in the agent, or some application interaction that's causing the problem and advise from there. 

OK -- that's a mouthful, I'll stop there :)  If you have any follow up questions let us know -- otherwise we'll keep an eye out for those answers.

**Comment by mastermatt** [comment]
> What flags are you invoking ts-node with when you run the application?

The Docker image that Kubernetes deploys is based off of `node:10-alpine` and launches the proc with:
`node -r ts-node/register/transpile-only --max-old-space-size=512 server.ts`  

The max old space flag is set to match the k8 pod limit so Node doesn't OOM on us and k8 can send a SIGINT to gracefully kill the proc first.

> If you manually compile/transpile the code to native javascript and run with node, is the leak present?

This is the next step I'm going to take, but it's not trivial on this app, so I posted this issue first on the off-chance you responded with "oh yeah, that's because x, y, z...".
We do have several other Node apps written in TS, all smaller in codebase and resource usage, that do pre-transpile. Same versions of Node, New Relic, most tooling etc. And the leak does not seem present, but they also have a lot less throughput and I have determined that throughput is a factor in this case. 

> What version of express are you using?

4.17.1. Current latest. Routing provided by [`swagger-tools`](https://www.npmjs.com/package/swagger-tools) 0.10.4

> What are your express API endpoints doing?

The app is heavily I/O bound. It almost exclusively makes outbound HTTP requests and does CRUD w/ the `mysql` driver.
There is also some ElastiCache communication via `memcache-plus`.

> Are you using any third party promise libraries?

Not directly but Bluebird 3.7.2 is a sub dep.

> Is the set of endpoints you have small enough that it would be possible to run some tests and determine if there's a specific endpoint with this leak, or its all of them?

Probably not. But we could look into it. The routes on this app can be grouped into two buckets. 1) CRUD in db then return JSON. 2) CRUD in db, make a series of outbound HTTP requests, CRUD in db, return JSON. Nothing really fancy outside of the complexities of which external services to call. 

> What other libraries are you using to fetch data?

Besides the datastores listed above, I dug into the sub-deps and see HTTP requests are made via `request`, `superagent`, and `got`. 


I'm still running some more debugging experiments with different memory settings to see anything obvious falls out. After that, I'll look to have it converted to pre-transpiled and see if ts-node is the culprit. 

I know ts-node has had issues with performance around re-parsing files unnecessarily, but I haven't found anyone else having issues with ts-node retaining object references. 

I'm also going to dig around and see if there could be anyplace where a promise isn't resolved. I know this app does make a few outbound requests without awaiting them before responding to the inbound request. But those promises should still be resolving or rejecting, just not during the classic Transaction window.

**Comment by astormnewrelic** [comment]
Those sounds like good first steps @mastermatt.  It's super annoying, but these sorts of issues usually come down to some _very specific_ invocation that happens to leak because of some unanticipated interaction between the agent and a library.     

We'll be interested in hearing what you find out!  Best wishes.

**Comment by astormnewrelic** [comment]
@mastermatt just wanted to check in to see if you managed to rule anything our here, or if you're still looking for a window where you can give things a try?

**Comment by mastermatt** [comment]
We went through the process of running the app without ts-node over the weekend and the problem still persists. 

I still haven't discovered the culprit at this point, but I'll close this issue as ts-node seems to be the wrong angle. 
It appears that something is holding onto the inbound request, which in turn is retaining pointers to NR Transactions etc, which rise to the top when debugging since they take relatively more memory. 
When I find the issue, I'll try to remember to post a follow up here for those curious.

**Comment by fantun3s** [comment]
Hi! I can also experience the same issue, and I tried to trace back any object out of newrelic module that could be holding a reference to it without success.

![image](https://user-images.githubusercontent.com/2700043/85878289-5d9ef300-b7d0-11ea-93c6-5f116fce07e8.png)

Node: 12.18.0
newrelic: 6.0.0

**Comment by raoulus** [comment]
Hey everyone,

we are facing the same problem. Heap dump shows more or less the as @fantun3s described.

Our app is proxying requests and making calls to external APIs. The memory grows very quickly. Only when NR is not loaded at all the memory seems to be stable.

I am very interested to know how all the others resolved this issue?

**Comment by mastermatt** [comment]
My conclusion was that NR was not the cause of the memory leak itself. There was something else that was holding on to HTTP requests. However, the NR agent tack objects onto the `IncomingMessage` instances making the memory leak much more noticeable. Even to the point of OOMing. 

@raoulus I'd be willing to bet that you still have a memory leak when NR is not loaded, but it's small enough that it's hard to detect unless you really put your app under load for a while.
