### ISSUE TITLE
Instrument what happens in binary called via `child_process.spawn`?

### ISSUE THREAD

**Issue by janpio** [newrelic/node-newrelic#385]
I have an external binary that is executed via `child_process.spawn()` that returns some data to my Node app - you could compare it to a database more or less. 

At the same time the logic in the binary is complex enough, that it would be interesting for me to instrument the individual segments inside it (e.g. sending one request into the binary, leads to many "database queries" being executed and data proceesing functions being called). 

How would I best get this information out of the binary and into the NR monitoring of my app? Right now I can only `newrelic.startSegment` on the method that calls the binary and get its information as a big black box.

**Comment by janpio** [comment]
It would be possible for me to return the timings from inside the binary with the data it returns anyway, but I am not sure if there is a way to tell node-newrelic that it should add "detail" to this big timing it just created, or split it up into smaller segments with duration x and y.

**Comment by astormnewrelic** [comment]
Nice to meet you @janpio, and it's great to see you working our APIs.  It always feels good when folks go beyond the basics with our agent. 

This repository is mainly for development of the Node Agent itself -- we don't get too into "how to use the API" here -- your best bet for that kind of help is over in [our explorer's hub forum](https://discuss.newrelic.com/).

...

But since I can't help myself -- it sounds like the binary you execute via `child_process.spawn` returns data about how long things took, and you want to send that data to New Relic.  Our segment API only allows you to measure how long specific function calls take -- it does not allow you create arbitrary segments based on data. 

Your two choices here are 

1. Use the Node Agent to create custom metrics or custom events with the data, and then use New Relic Insights, Chart Builder or Alerts to query-for and chart this data

2. If possible, add instrumentation code to the binary itself.  This presumes you have access to the binary's source -- if it's truly a black box then this is not an option. 

We're going to close this issue out -- but we highly recommend continuing the conversation [over in explorer's hub.](https://discuss.newrelic.com)

**Comment by janpio** [comment]
Sorry for "abusing" the issues here - I will open a similar question in the Explorer's hub then.

...

But, fortunately, you already gave me an important part of the answer: The Node agent is indeed not meant to be able to just create segments based on data and thus does not have the functionality I was hoping for. That's a shame, but I totally understand why that is.

> If possible, add instrumentation code to the binary itself. This presumes you have access to the binary's source -- if it's truly a black box then this is not an option.

I do have access to the binary, so I would in theory be able to add instrumentation in there. This also seems like a better, more integrated solution that trxing to work around it with custom metrics and events and then try to build some dashboard manually.
I assume this would be a use case for distributed tracing where the binary would be its own "app" then, but because of some magic it would be displayed instead of the current "black box" segment in the node app tracing?

**Comment by janpio** [comment]
Via some unrelated research into a Rust library, I came across [`newrelic_set_segment_timing()` in the C API](https://newrelic.github.io/c-sdk/libnewrelic_8h.html#a3a803e3956f754082fb8aaee9154b158) which is basically what I asked for above - but for C of course. Having this in Node would be neat... Just saying ;)
