### ISSUE TITLE
Lazy initialization / configuration

### ISSUE THREAD

**Issue by EdgarPost** [newrelic/node-newrelic#460]
## Is your feature request related to a problem? Please describe.
When using `node-newrelic`, the only way to configure the instance is by using a `newrelic.js` or an environment variable. It's a bad practice to leave secrets such as the license key in your codebase and while an environment variable is somewhat more secure, it is still visible in the console when using AWS Lambda for instance.

In my specific use case I am using AWS Lambda and I want to retrieve the license key from AWS SecretsManager. This means I need to do a call to this service and since this is async, it is always "too late" to configure `node-newrelic` since this is immediately intialized.

## Feature Description
I would like to initialize `node-newrelic` manually in which you can pass a configuration object. To make it backwards compatible you can leave the default export use a named export, such as `createInstance`. 
This does mean that `node-newrelic` should not break or give warnings on a missing `newrelic.js` or `NEW_RELIC_NO_CONFIG_FILE`.

For example:
```javascript
import { createInstance } from 'newrelic';

const newrelic = createInstance({
  app_name: ['My Application'],
  license_key: 'license key here',
});
```

## Describe Alternatives
I have considered using a Node.js child process or workers, so first retrieving the secrets from AWS SecretsManager, then setting a custom `process.env.NEW_RELIC_LICENSE_KEY` and then spawn a subprocess, but seems to tedious just to avoid this problem.

## Additional context
I would be willing to help adding this feature.

## Priority
Really Want

**Comment by astormnewrelic** [comment]
Hey Edgar, nice to meet you and thanks for the feature request.  If it's OK, we have a few questions that will help us narrow in on the right solution here.

Have you tried just not configuring a licence key for the agent in the lambda environment?  It looks like [the `license_key` check](https://github.com/newrelic/node-newrelic/blob/46f76a97cab90762d1b73068661e61ae5ea0652f/lib/agent.js#L218
) is [_after_](https://github.com/newrelic/node-newrelic/blob/46f76a97cab90762d1b73068661e61ae5ea0652f/lib/agent.js#L215) we return early for serverless startup. This means it ~should~ might be possible to run the agent itself without configuration a license key.  Have you tried this?  Is so, has it worked for you?

Second -- you said that

>  I want to retrieve the license key from AWS SecretsManager. This means I need to do a call to this service and since this is async, it is always "too late" to configure node-newrelic since this is immediately intialized.

I'm not immediately familiar with the AWS Secrets API -- would using an async function and `await` help  you here?  Or does the is the API design of the secrets API built in such a way that doing this with the agent is still impossible?

If you can let us know if the above two suggestion remove the need for this feature request, let us know.  If not ...

When we've tried to approach this problem in the past, one challenge we faced was [our patching of Node's module loading](https://github.com/newrelic/node-newrelic/blob/46f76a97cab90762d1b73068661e61ae5ea0652f/lib/shimmer.js#L355).  This _needs_ to be the first thing to happen in a program.  If a module is loaded _before_ the agent loads, then the agent won't have a chance to see that module load because future calls to `require` will use cached values.

Do you have any thoughts/idea on how the proposed `newrelic.createInstance` method might be able to work around this problem?

**Comment by EdgarPost** [comment]
Hi @astormnewrelic, thanks for your swift reply! Nice to meet you too.

I am fairly new to New Relic's agent in general, but also in combination with Lambda. I read the ['official' solution by using two Lambda's](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda) - is this what you are refering to? 

In that way if you're enabling `NEW_RELIC_SERVERLESS_MODE_ENABLED` in the second Lambda and it will collect data from CloudWatch. But then you still need to inject `NEW_RELIC_LICENSE_KEY` into the first Lambda. Correct me if I'm wrong.

In our case we are using just one Lambda with the agent directly.

Regarding your second point, I tried using async / await, but that's just syntatic sugar over a callback function, so it's still asynchronous. I added a sample of AWS SecretsManager below.

AWS SecretsManager helps securing secrets by not exposing them in codebases or environment variables. And it also offers rotation, so you can have different database credentials every hour, for example. In the case of new relic we won't have rotation, but we'd still like to not expose them in our consoles.

Stripped down code for retrieving secrets from AWS SecretsManager:

```javascript
import { SecretsManager } from 'aws-sdk';

const secretsManager = new SecretsManager();

secretsManager.getSecretValue(
  { SecretId: process.env.AWS_SM_SECRET_ID },
  (error, secretValue) => {
    const { licenseKey } = JSON.parse(secretValue);

    // use licenseKey to initialize newrelic here?
  }
);
```

**Comment by astormnewrelic** [comment]
> I am fairly new to New Relic's agent in general, but also in combination with Lambda. I read the 'official' solution by using two Lambda's - is this what you are referring to?

Ah, yes, apologies. That is what I was referring to.  This "two lambda" approach is New Relic's current approach to supporting Amazon Lambda.  You are correct that [the second lambda](https://github.com/newrelic/aws_s3_log_ingestion_lambda) requires a license key -- but this Lambda function is written in python, and not NodeJS.  If you need help getting setup with our official lambda solution one of our official support channels ([Explorer's Hub](https://discuss.newrelic.com) or the [Support Portal](https://support.newrelic.com/)) is probably a better place to head for help.  Our docs [on Enabling Lambda](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda) may also be of interest. 

Regarding getting the agent working by itself in a Lambda -- I don't want to discourage you because Open Source, [have it your way :) ](https://www.youtube.com/watch?v=KJXzkUH72cY), but the license key issue you're describing will only be the first hurdle.  

In our early attempts to get an agent working with a single lambda, we found the lambdas did not stay open long enough for the initial connection handshake to finish, which means the agent installed but never sent any data.  Have you found this to be a problem with your child process approach?

**Comment by rr0214** [comment]
This is not a priority given our strategic direction. We are closing this one out.

**Comment by metaskills** [comment]
If you want to, you can use this Lambda project (layer or container) to get SSM Parameters injected as real ENV vars. https://github.com/customink/crypteia Hope that helps with this issue.
