### ISSUE TITLE
Browser agent injection examples for react and links to documentation

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic#498]
Seems like some extra guidance would be useful here to help reduce user confusion and support requests.

Spending some extra time to form strong opinions on what we recommend would be good.

I'm guessing copy-paste will continue to win as what is the best approach. Even if not, we'll want to mention this as an approach and link to the appropriate documentation. While that doesn't really involve our agent at all at that point, customers are still looking to our agent to get help.

We'll also want an example using the API for injection via supported approach.

**Comment by michaelgoin** [comment]
size: medium

**Comment by fourpastmidnight** [comment]
I created a React NodeJS app last year and ran across a project called [Yarn.build](https://yarn.build) ([source](https://github.com/ojkelly/yarn.build)). When running that over my project, it produced an `entrypoint.js` file. Unfortunately, I couldn't use yarn.build at that time, _BUT_, the `entrypoint.js` file turned out to be very useful for me in allowing me to easily start my app. Instead of needing to `node.exe -r .pnp.js dist/index.js`, I can simply `node.exe entrypoint.js`. 

Using that concept, it might be possible to suggest that users create an entry point file, such as this one below:

```js
"use strict";
// If using Yarn 2/3...
// This justs enables Yarn to override NodeJS's default module resolution logic
// to load npm modules out of Yarn's module cache instead of `node_modules`.
const pnp = require('.pnp.js').setup();

// Load newrelic before your app so newrelic can instrument everything...
const newrelic = require('newrelic');

// Now require your application and create an ES Module with your application
// being the default export.
const index = require('./location/to/index.js');
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = index;
```

**Comment by fourpastmidnight** [comment]
Oops, I thought this was about the NodeJS agent, but it seems this issue is about the Browser agent. The two are easily confused since they both deal with "Web" technologies, and you can enable the browser agent from within the Node JS agent (at least, on the application side).

**Comment by fourpastmidnight** [comment]
So, today I tried to get the New Relic browser agent installed in my React Node JS application. The difficulty here was that I've used `create-react-app` to create my React JS app. (I'm not a web developer by day, I'm a DevOps guy, but I can manage 😉.) Anyway, I didn't want to use the copy/paste method, so I used server-side injection to accomplish this. I think this is probably the best way to go about this for React folks. I should also mention that I'm using Yarn 2 instead of NPM for Node package management.

When using `create-react-app` (CRA) to create your React application, it creates a standard `index.html` page for you. When you build your application, CRA uses Webpack along with the HTMLWebpackPlugin to inject a script tag as the last element of the `body` element which takes care of "bootstrapping" your React application in the browser. I host my "React" assets under the `/ui` folder of my Express JS server.

Modify your CRA `index.html` page and add a script block after the `<meta charset='utf-c' />` element, as instructed by the New Relic documents. I also took the liberty of restructuring the elements inside of the `<head>` element so that things like the document's title and description were also near the top to help with SEO:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href=A"%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>My Awesome App</title>
    <meta name="description" content="This is the awesome-est app ever!!" />
    <script id="#nreum">
      // Placeholder for the New Relic browser agent loader script to be injected
      // server-side
    </script>
    <!-- ... other head elements go here ... -->
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

Now, in your ExpressJS `server.[jt]s` file, where you declare all of your routes, you'll use server side injection. I made use of the `cheerio` npm package to do this. I'm only going to show the relevant code:

Add the following to your project:

```sh
yarn workspace server add cheerio@1.0.0-rc10  # <-- There was an issue with the latest RC, so use this
```

```ts
import path from 'path';
import fs from 'fs';
import cheerio  from 'cheerio';
import newrelic from 'newrelic';
import express, { Express, Request, Response } from 'experss';
// Any other imports you might need...

const app = express();
app.use(express.json());
app.get('/', (_, res) => {
  // Get the new relic browser agent loader script
  const browserAgentLoader = newrelic.getBrowserTimingHeader();

  // Get the landing page for our CRA app
  const index = fs.readFileSync(path.join(__dirname, './ui', 'index.html'), 'utf8');
  const $ = cheerio.load(index);

  // Find the script placeholder and replace it with the browser agent loader script
  $('#nreum').replaceWith(browserAgentLoader);
  res.send($.html());
});

// Setup the static assets route
// Be sure this comes after the route above, or your server-side injection won't work.
// I got "lucky" and ran into this issue...
app.use(express.static(path.join(__dirname, './ui')));

export default app;
```

And that's it. When I reloaded my app with the browser Dev Tools open, I could see the `<script>` placeholder element get replaced with the browser agent loader script, and then going into New Relic, I could see my browser application.

Neat! I hope this can help you with your documentation efforts for React folks.

**Comment by coreyarnold** [comment]
@fourpastmidnight This is some great information. Thanks so much for your help in making examples like this clear for others. We'll look to incorporate this into documentation and examples. We also have a [newrelic-node-examples](https://github.com/newrelic/newrelic-node-examples) repo for this very purpose. Thanks again!

**Comment by bizob2828** [comment]
We have examples of react within Next.js for both [app router](https://github.com/newrelic/newrelic-node-examples/blob/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router/app/layout.js) and [pages router](https://github.com/newrelic/newrelic-node-examples/blob/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-legacy/pages/_document.jsx), this might be enough for react but we can add to this app to show how to inject into [express app](https://github.com/newrelic/newrelic-node-examples/blob/58f760e828c45d90391bda3f66764d4420ba4990/simple-express-app/index.js)
