### ISSUE TITLE
Question: is there a way to make newrelic log an error

### ISSUE THREAD

**Issue by dodozhang21** [newrelic/node-newrelic#613]
Hi,

We are working on cache strategy that'd serve stale while revalidate. We want to make newrelic log errors but not send error status to the browser. It's like this

cache expired, get from origin, origin erred, make new relic log error but serve from cache as 200 to the browser.

Is that possible or is new relic not the right tool for this purpose?

Thanks

**Comment by michaelgoin** [comment]
Hi @dodozhang21,

You can use the `noticeError(err, optionalAttributes)` API method to notify New Relic of the error. If you handle the error, so that the agent does not detect it as unhandled, and call noticeError you should get the behavior you are looking for.

https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api#noticeError

**Comment by dodozhang21** [comment]
@michaelgoin  thank you!

**Comment by michaelgoin** [comment]
No problem! Happy to help. 

Closing this out as we've answered the question.
