### ISSUE TITLE
Add the option to exclude expected errors by error message in Java and Node.js agents

### ISSUE THREAD

**Issue by itaykor** [newrelic/node-newrelic#624]
## Is your feature request related to a problem? Please describe.
We often find ourselves wanting to exclude expected errors, but sometimes the granularity of a class (and certainly an HTTP status code) isn't good enough.
This is because we sometimes have an error which happens for several reasons, and we only want to exclude one of the cases.
Another issue is that sometimes this error is thrown by some framework (whether internal or external) and you can't control it or wrap it with another exception.

## Feature Description
We would like to be able to exclude expected errors based on error message, and not just by class or HTTP status.

## Additional context
I recall there was once an option to ignore errors by error message, though I can't find it anymore.
Therefore, I hope it shouldn't be a lot of work to restore this functionality and apply it to the 'exclude' section.

## Priority
Must Have

**Comment by michaelgoin** [comment]
Hi @itaykor,

The configuration item you are looking for in the Node.js agent is `ignore_messages`. You can find that here on our configuration documentation: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#error_ignore.

This configuration takes a collection of messages to ignore per error type similar to below:

```js
error_collector: {
        /* ... */
        ignore_messages: {"Error":["Undefined", "Out of time"]}
        /* ... */
    }   
```

While I'm not involved with the Java agent, I'm pretty sure they have the same configuration.  Doing a quick search on the Java agent config documentation, it looks like it is documented here: https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file#ec-ignore_messages.

It is worth noting for the Node agent (unsure about Java), the `newrelic.noticeError()` API calls do not honor this configuration.

Hope that helps!

Closing out since the feature exists, but don't hesitate to reach out if you have issues.
