### ISSUE TITLE
Question: can we ignore certain errors

### ISSUE THREAD

**Issue by dodozhang21** [newrelic/node-newrelic#625]
Hi, we have some legit 400 errors we throw via the application, is there any way using new relic lib to make new relic ignore these errors so they are not counted toward the total error rate?

**Comment by michaelgoin** [comment]
Hi @dodozhang21,

See the 'ignore_status_codes' configuration for the error collector here: https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration#error_collector.

Your configuration should look something similar to:

```js
    /* ... */
    error_collector: {
        ignore_status_codes: [400, 404]
    }    
    /* ... */
```

We also have an 'expected' error set of configuration if you want the errors to show up on the 'Errors' page but not impact error counts.

**Comment by dodozhang21** [comment]
@michaelgoin i don't want to ignore all 400 so I tried these
```
  error_collector: {
    expected_messages: { BadRequest: ['Bad Request'] },
    expected_classes: ['BadRequest'],
  },
```
and our BadRequest class, it doesn't seem to work
```
export class HTTPError {
  constructor(status = 500, message = 'Unknown Error') {
    const err = Error.call(this, message);
    err.name = 'HTTP Error';
    err.status = status;
    return err;
  }
}

export class BadRequest extends HTTPError {
  constructor(message = 'Bad Request') {
    super(400, message);
  }
}
}
```

**Comment by michaelgoin** [comment]
I'm guessing it is because of how you are constructing errors. The super constructor is returning a new error object and setting the `err.name` property to the same thing. So I'm guessing even the BadRequest error type is 'HTTP Error'. For an error object, we will grab `error.name`, or `error.constructor.name` if `error.name` is not populated.

Just tested real quick locally to confirm with `throw new BadRequest()`. Notice the error type in the stack trace:

```
Error [HTTP Error]: Bad Request
    at new HTTPError
 ```

When doing child error inheritance in Node/TypeScript, you'll typically want to ensure the name is updated appropriately. But as far as our configuration is concerned, you could also check for the 'HTTP Error' class.

Keep in mind the 'expected' versions will still report the errors to New Relic but won't impact the error rate metrics.  So if you want them to not show up at all, you'll need to use the 'ignored' counterparts. Expected may be what you want but clarifying again. Also, errors reported by the `noticeError()` API do not honor these configurations.

**Comment by dodozhang21** [comment]
i see i will try that thanks.
