### ISSUE TITLE
Wrong APM data after enabling new promise tracking

### ISSUE THREAD

**Issue by artur-ma** [newrelic/node-newrelic#729]
Looks like the agent sends wrong APM metrics after enabling new promise tracking

## Description

After enabling the feature NEW_RELIC_FEATURE_FLAG_NEW_PROMISE_TRACKING
we see a drop in throughput from 1.5k RPM to ~10 RPM
which is wrong since the overall system stayed with the same throughput 
we are not doing anything special with the "post resolve" on the promise

## Your Environment

Node 14
inside k8s pod
**Fastify** as web framework

**Comment by michaelgoin** [comment]
@artur-ma thank you for trying the feature-flag so quickly and sorry for the troubles.

Unfortunately, a change like this can change can have a bit of a cascading effect due to a change in assumptions. We tried to test out several scenarios but looks like we missed some, which we knew was a bit of a risk. Hopefully, we can track down this scenario and find a straightforward resolution.

1.5k to 10 is a huge drop. I wonder if there ended up being some state conflation in this scenario where somehow the same transactions were used over and over again.

Anything you can share about how you are setup using fastify and your promise usage would be great to help us reproduce. Particularly, code samples.

If you are willing to capture trace-level logs, that would also be extremely helpful. In that case, I'd recommend opening a support ticket and sharing via the ticket as the level of detail we capture in trace logs can expose details such as license key, route params, etc. that wouldn't be good to have publicly visible.

**Comment by artur-ma** [comment]
> 1.5k to 10 is a huge drop. I wonder if there ended up being some state conflation in this scenario where somehow the same transactions were used over and over again.

Just to clarify, there was no real drop in throughput, 
I also ran autocannon, to see if it grows, but it didn't the throughput in autocannon was about 1k requests/min, but on APM dashboard the values didn't change

So actually there was no degradation in performance, only metric report.

> Anything you can share about how you are setup using fastify and your promise usage would be great to help us reproduce. Particularly, code samples.

I will try to have some reproducible example for you, basically we don't have 
any plugin on our fastify except fastify-compress 

Each request:
* Gets the data from redisDB (using ioredis) and returns it as a response 
* Sends Kafka message(KafkaJs) withing non-awaited promise

**Comment by michaelgoin** [comment]
@artur-ma The latest release v7.3.1 *may* resolve your issue. Don't have enough details to know for sure but seems similar based on what you have shared. Would be worth testing out again.

**Comment by artur-ma** [comment]
@michaelgoin Looks like it is fixed, and also we see the growth of throughput 5k => 6.5k after enabling the flag

Thanks!

**Comment by michaelgoin** [comment]
@artur-ma thank you for letting us know! Glad to see a noticeable throughput improvement. I'm curious (if you can tell) what the memory comparison looks like? With that much increase in throughput, there's a chance it actually went up but I hope it did so at a much lower percentage than prior or would be great to know if it actually still went down or stayed relatively consistent.

No worries if too hard to tell at this point.
