### ISSUE TITLE
Instrument undici

### ISSUE THREAD

**Issue by artur-ma** [newrelic/node-newrelic#730]
## Is your feature request related to a problem? Please describe.
Undici is not using the native nodejs "http" module supported by node-newrelic

## Feature Description
Add instrumentation option for undici
https://github.com/nodejs/undici

It is a new ultrafast client 

## Priority
Must Have

https://github.com/nodejs/undici/issues/693#issuecomment-815525208

**Comment by carlo-808** [comment]
Thank you for the feature request @artur-ma. I was not too familiar with the undici package but it looks really interesting and does seem to have some apm hooks. We'll get this prioritized behind the other work we have in the queue.

**Comment by artur-ma** [comment]
Hey guys, since popularity of undici is growing, the discussion now how to implement APM instrumentation around it, could you add please your input here please

@carlo-808 @michaelgoin @bizob2828 
https://github.com/nodejs/undici/issues/980

**Comment by bizob2828** [comment]
@artur-ma apologies for the delay.  I'm going to start digging into the linked issue and corresponding draft PR to see if it will fit our needs

**Comment by bizob2828** [comment]
Added a prototype PR that shows support for this library https://github.com/newrelic/node-newrelic/pull/901. The notes in PR state we need an issue to be fixed in Undici

**Comment by liesislukas** [comment]
i try to use newrelic on node v18 with native `fetch` api and i think it is using undici under the hood. And it's not able to keep track of full transaction like i posted at forum: https://discuss.newrelic.com/t/node-i-see-two-separate-traces-but-no-connection-between-micro-services/192927

**Comment by bizob2828** [comment]
Hi @liesislukas undici instrumentation is not the same as fetch.  You are correct and that global fetch in Node.js is undici's fetch but due to the mechanisms of exporting the global fetch namespace of Node.js runtime, the process to instrument is different.  We have it on our backlog but it hasn't become a priority just yet.  I saw you commented on another issue.  At this point it's best to file a feature request for global fetch support.  We're currently in this transition between GitHub issues and a public jira instance and the ticket to track this work is not accessible to the public.

**Comment by kibertoad** [comment]
@liesislukas Node fetch is also 5-6 times slower than direct undici usage, so you may consider using that.

**Comment by bizob2828** [comment]
@kibertoad do you mind posting the evidence to this? I was unaware of such an impact 😬

**Comment by kibertoad** [comment]
@mcollina Could you please comment on this? I remember you mentioning on Twitter the perf difference, but I can't find the exact thread, it was a while ago. IIRC, difference is primarily due to the usage of Web Standard streams.

**Comment by liesislukas** [comment]
@kibertoad thanks for the tip on direct use. Though undici is not working with newrelic anyways, atm better insight into app is higher priority then max speed. For now using this npm package https://www.npmjs.com/package/cross-fetch and it works fine. There are other more important bottlenecks to prioritize. while exploring to get more networking speed next step may be trying out grpc but again, dev time spent there won't be spent elsewhere. undici support may be very little dev time investment for performance gain, at least from my position, hence hoping to see undici at newrelic.

**Comment by bizob2828** [comment]
@liesislukas can you tell me what's not working with undici instrumentation? It's current behind a [feature flag](https://github.com/newrelic/node-newrelic/blob/main/documentation/feature-flags.md#undici_instrumentation), did you enable it? We have plans to revisit undici and global fetch in the near future and make it generally available.  We have some rough edges to work out since this is our first foray into using the `diagnostics_channel` events.  It does not place nicely with our transaction based model in certain cases.

**Comment by liesislukas** [comment]
can't guarantee i enabled flag successfully, i saw it, not sure if decided to give it a go or not. my use case was like so:

1. running RESTfull backend A
2. running RESTfull backend B
3. backend A calls backend B with native fetch

i saw in newrelic 2 traces instead of 1, googled around, found undici issues, tried resolving, failed, took too long, switched to npm package cross-fetch and now it works fine.

**Comment by bizob2828** [comment]
@liesislukas we can't track native fetch.  But if you did try replacing with undici and it still didn't work if you can provide some repro steps I can take a peek.  We're interested in ironing out any issues to make this generally available

**Comment by kibertoad** [comment]
@bizob2828 OK, found original thread where this was discussed, although I misremembered a specific number, which was not mentioned, but difference is significant, apparently: https://twitter.com/matteocollina/status/1589234227215622144?s=20
