### ISSUE TITLE
Events are not sent to NR on shutdown of agent

### ISSUE THREAD

**Issue by slambdev** [newrelic/node-newrelic#789]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

On occasion, events are not sent to NR! In our code base, we have had issues with this in the past so we added the following code

```
    logger.info('Starting to shutdown newrelic agent', { state: newRelicInstance.agent._state });

    const shutdown = util.promisify(newRelicInstance.shutdown).bind(newRelicInstance);

    await shutdown({ collectPendingData: true });

    logger.info('Finished shutdown of newrelic agent....', new Date());
```

Unfortunately, this did not solve all of our problems, and we are still getting intermittent data loss in NR.

## Expected Behavior

When the program exits, all data is send to NR!

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

We added some logging and noticed a pattern on the past few runs. On runs where the agent's state was "started", the agent would send data to NR and shutdown properly. When the agent's state is "connected", data would **not** be sent to NR.

Looking through the codebase, I noticed the following line:

https://github.com/newrelic/node-newrelic/blob/f0322c16517fa51f1d3564eb7c48247a24456e50/api.js#L1540 

I _believe_ the problems stems from the above!

## Steps to Reproduce

Unfortunately, this is not a very easily reproduce-able bug. With no code changes, the job will inconsistently send/not send data to NR.

## Your Environment

- Cronjob in Kubernetes (v1.19) on IBMCloud
- NewRelic agent version: 7.5.0
- Node version: 16.2.0

**Comment by bizob2828** [comment]
@slambdev thanks for bringing this to our attention!  My initial question is how long does the cronjob run? 

Regarding: https://github.com/newrelic/node-newrelic/blob/f0322c16517fa51f1d3564eb7c48247a24456e50/api.js#L1540, we need the agent to be in the started state because of all the reconfiguring of the agent and it won't be safe to shutdown and reliably send data to NR1.  

We will probably consider another option to shutdown that waits for the agent to be started or introduce a new api that waits for startup before executing script.  I will talk to our PM to get this prioritized

**Comment by slambdev** [comment]
Thanks for getting back! The job takes about 15 min to run. At the beginning of our job we include the following code to validate that the agent is running!

```
async function validateNewRelicAgentStarted(newRelicInstance: any): Promise<void> {
    if (process.env.NODE_ENV !== 'production') {
        return;
    }
    let intervalWaited = 0;

    logger.info('Validating newRelic agent state');

    const newRelicAgent = newRelicInstance.agent;

    // Check if agent_enabled is set to false. If it is, then return immediately.
    if (!newRelicAgent || !newRelicAgent.config.agent_enabled) {
        return;
    }

    if (newRelicAgent._state === 'stopped') {
        logger.info('NewRelic agent was stopped. Starting again...');
        const start = util.promisify(newRelicAgent.start).bind(newRelicAgent);

        await start();
    }

    while (intervalWaited < MAX_WAIT_TIME_MS) {
        const { _state: newRelicState } = newRelicAgent;

        logger.info('_state', newRelicState);

        if (newRelicState === 'started') {
            break;
        }

        intervalWaited += WAIT_INTERVAL_MS;

        await wait(WAIT_INTERVAL_MS);
    }

    if (newRelicAgent._state !== 'started') {
        throw new Error('NewRelic agent failed to start up');
    }

    logger.info('NewRelic agent successfully started up');
}
```

**Comment by michaelgoin** [comment]
Currently looking into this via support channels. Internal Jira: 10314

**Comment by michaelgoin** [comment]
I was able to setup a simple reproduction (attached to the Jira as I copy-pasta'd some client code examples). 

We have an issue with the shutdown API when restarts occur, regardless of the timing. When the agent restarts, the state is never getting set to 'started'. It is staying at 'connected'. As such, this handler is never hit: https://github.com/newrelic/node-newrelic/blob/f0322c16517fa51f1d3564eb7c48247a24456e50/api.js#L1552-L1554.

In this case, Node does not have any active timers and shuts down the script (for my test case) without fully executing the remaining code and waiting for the shutdown promise to resolve. With 'started' being set appropriately, everything seems to chug along fine.

Seems like there could still be a small risk with regards to timers, since we always `unref` to avoiding holding processes open but I was unable to force a breakage there. If that ever does come up, we can someday modify the shutdown API timeout to keep a reference (since users are opting into keeping the process open via the API) and then guide users to set a timeout. I don't think we should cross that road right now.

This is likely the simplest location for ensuring the state is correct: https://github.com/newrelic/node-newrelic/blob/main/lib/collector/api.js#L518-L520. A better/more-consistent agent location that is used by both normal startup and restart paths likely exists or can be created. Depending on the effort, we may want to do a quick fix and then schedule a longer-term fix or just go for more optimal up-front.
