### ISSUE TITLE
High number of TraceSegments hanging around

### ISSUE THREAD

**Issue by jbroomer** [newrelic/node-newrelic#998]
## Description

I am noticing a fairly high number of TraceSegments being kept around in memory (~30k). I have done quite a bit of the Google to find similar issues/resolutions but have not found anything that really answers this question.

![Screen Shot 2021-12-08 at 4 51 42 PM](https://user-images.githubusercontent.com/38018109/145291101-403dff3f-587c-4c0e-a1be-26e060ea00dd.png)

## Expected Behavior

I would have expected these TraceSegements to be handled by the GC, this seems very high.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
Node version: 10.24.1
newrelic version: 7.5.2
  * I have `NEW_RELIC_FEATURE_FLAG_NEW_PROMISE_TRACKING` enabled
 
This service makes a bunch of downstream requests to craft its response and I am making requests using Axios and have `keep-alive` enabled.

**Comment by michaelgoin** [comment]
Hi @jbroomer,

That does indeed look excessive. Typically, I'd expect the promise tracking feature flag to help unless there's a large number of promises not being resolved. Without that flag, sometimes we'll have a ton in memory as it can take a couple GC cycles for them to clear.

That being said, there's a chance we have a bad interaction with Axios and keep-alive. We have resolved an issue with Axios in the past due to them assigning promises on errors which we had a handle on. That particular issue was resolved in 7.2.1. Although, depending on your throughput/promise-usage perhaps a lot could still be in memory for the life of transactions and getting cleared late. There's always the chance there is an existing but very tiny promise leak that looks way worse with our agent attached, as well. If for some reason there's a batch of promises that are not resolved or destroyed and we've been tracking context with those, we'll end up with entire segment trees stuck in memory.

The best way to work through these sorts of issues is to work with our support team over at support.newrelic.com. This way you'll get a bit more hands-on support and we can get more sensitive details about your application you likely don't want out in public.  For memory involved issues like this, we'll end up requesting heap snapshots so we can see where memory is being held. We'll need a minimum of 2 but typically ask for 3 (one after startup, one after 5-ish minutes, one after 5-ish more minutes). They'll also ask for some trace level logs (captured separate from the heap snapshots) and likely we'll also want the axios version.

**Comment by jbroomer** [comment]
I temporarily disabled the `keep-alive` option and the memory consumption seems more stable. There are definitely fewer TraceSegments. This isn't super high on the current list of priorities so I am going to close this issue. When the team eventually gets back to it, if we determine we still need to seek resolution with newrelic, we will go down the suggested support path! Thank you for taking a look at this
